version: 2
sources:
  - name: raw
    schema: neobank
    description: neobank raw data source
    tables:
      - name : devices
        identifier: devices
        columns:
          - name: user_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name : notifications
        identifier: notifications
        columns:
          - name: notification_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name : transactions
        identifier: transactions
        columns:
          - name: transaction_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name : users
        identifier: users
        columns:
          - name: user_id
            description: primary key of the table
            tests:
              - unique
              - not_null