version: 2
sources:
  - name: raw
    schema: neobank
    description: neobank raw data source
    tables:
      - name : devices
        identifier: devices
        columns:
          - name: user_id
      - name : notifications
        identifier: notifications
      - name : transactions
        identifier: transactions
        columns:
          - name: transaction_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name : users
        identifier: users
        columns:
          - name: user_id
            description: primary key of the table
            tests:
              - unique
              - not_null
      - name : mcc_description
        identifier: mcc_description
        columns:
          - name: ea_merchant_mcc
            description: primary key of the table
            tests:
              - unique
              - not_null          
      - name : user_id_score_rfm
        identifier: user_id_score_rfm
        columns:
          - name: user_id
            description: primary key of the table
            tests:
              - unique
              - not_null